#version: '3.9'
services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: aether_invest
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports: ["3306:3306"]
    volumes: ["mysql_data:/var/lib/mysql"]

  neo4j:
    image: neo4j:4.4.48
    container_name: neo4j
    ports: ["7474:7474", "7687:7687"]
    environment:
      NEO4J_AUTH: neo4j/password
      #NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_security_procedures_allowlist: apoc.*
      NEO4J_dbms_memory_heap_initial_size: 2g
      NEO4J_dbms_memory_heap_max_size: 4g
      NEO4J_dbms_memory_pagecache_size: 2g
    volumes: 
    - neo4j_data:/data
    - ./import_csv:/import_csv
    - ./plugins:/plugins
    restart: unless-stopped

  # milvus:
  #   image: milvusdb/milvus:v2.5.0
  #   ports: ["19530:19530"]
  #   volumes: ["milvus_data:/var/lib/milvus"]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  # backend:
  #   build: ./backend
  #   depends_on: [mysql, neo4j, milvus, redis]
  #   environment:
  #     MYSQL_URI: mysql+aiomysql://user:pass@mysql:3306/aether_invest
  #     NEO4J_URI: bolt://neo4j:7687
  #     NEO4J_USER: neo4j
  #     NEO4J_PASSWORD: password
      ##MILVUS_URI: http://milvus:19530
  #     REDIS_URL: redis://redis:6379/0
  #     SENTRY_DSN: ${SENTRY_DSN:-}
  #     BOCHA_API_KEY: sk-cc7031251f38414ba059473cb0e92384
      
  #   ports: ["8000:8000"]

  # celery_worker:
  #   build: ./backend
  #   command: celery -A app.celery_app worker -l info --pool=gevent --concurrency=50
  #   depends_on: [redis, mysql, neo4j]

  # celery_beat:
  #   build: ./backend
  #   command: celery -A app.celery_app beat -l info
  #   depends_on: [redis]

  prometheus:
    image: prom/prometheus
    ports: ["9090:9090"]
    volumes: ["./prometheus.yml:/etc/prometheus/prometheus.yml"]

  grafana:
    image: grafana/grafana
    ports: ["3000:3000"]

volumes:
  mysql_data:
  neo4j_data:
  # milvus_data: